### ISSUE TITLE
Mult Link selection 'n theme

### ISSUE THREAD

**Issue by mrochaaa** [jingyu9575/multithreaded-download-manager#65] opened 2019-07-12 14:29 UTC
Please add multi links selection to context menu function, if I select 10 link and go to context menu, add 10 links together, 

if possible add a dark theme,

setting to open new download window as popup

thanks

**Comment by Onurtag** [comment] 2019-07-13 12:14
You can use this as your custom CSS: https://gist.github.com/Onurtag/1ea462f330a8cc26d4b72d3023966f65 

To the Developer: Feel free to add this as a dark theme option. No need to credit me.

**Comment by jingyu9575** [comment] 2019-07-13 19:58
> add multi links selection to context menu function

Are you suggesting a feature to select a paragraph, and then right-click to download all links in that paragraph? 

A limitation is that one extension can only add one context menu, and if more than one is proposed, they will be collapsed into a submenu. Not sure if it is possible to workaround this.

> setting to open new download window as popup

It is possible to open the panel in a new window, by right-clicking the toolbar icon.

---

@Onurtag Thank you! I'll need to test it again though, as there are some changes in the new version in development.

**Comment by mrochaaa** [comment] 2019-07-14 23:41
@Onurtag  thanks

@jingyu9575 when I highlight 3 links in an page, using context menu, the plugin download only one, ideal is download 3, if need submenu I think this is no problem for any user, because today MDM is an One Link Downloader, it can be an Multi Link Downloader, like Downthenall. 

About window in popup, I say an setting to open not the main window, but the "New Download Prompt" in the button popup

**Comment by jingyu9575** [comment] 2019-07-16 15:42
> when I highlight 3 links in an page, using context menu, the plugin download only one, ideal is download the 3 selected (highlighted) links

Understood. I'll see how to implement it.

> the "New Download Prompt" in the button popup

Firefox does not allow opening the button popup without clicking on extension UI, [to prevent "abusive and intrusive practices"](https://bugzilla.mozilla.org/show_bug.cgi?id=1341126#c0).

> add multi links from clipboard

The next verison v2 will have this feature:

![图片](https://user-images.githubusercontent.com/8923139/61308629-38191380-a823-11e9-9882-dbec2bfb1e87.png)

**Comment by mrochaaa** [comment] 2019-07-22 21:56
very good, thank you

**Comment by jingyu9575** [comment] 2019-07-24 04:16
So this is how I implement the multi-link selection feature in v2 (still under development):

![image](https://user-images.githubusercontent.com/8923139/61764516-1b28a580-ae0c-11e9-8808-66bd8489c8cc.png)

After clicking the menu item, the link picker shows and the selected links are automatically checked. 

The menu items have to be collapsed into a submenu due to the limitation of Firefox. Also, I've seen some cases where the menu does not show if an image is at the beginning of the selection. I think it is Firefox's [Bug 1463002](https://bugzilla.mozilla.org/show_bug.cgi?id=1463002), although it is closed because the Firefox developer cannot reproduce it.

**Comment by mrochaaa** [comment] 2019-07-25 15:28
about multi link selection, is exactly this I said,  very good, about issues when have images, this is true, I know this issue, if you want, look the "FoxyLink" extension, seem this extension have an better link multi selection when have images, maybe his code can help.

**Comment by jingyu9575** [comment] 2019-07-25 22:28
FoxyLink is showing the selection's menu on unselected links too, so if this extension uses the same method, there will always be 2 menu items when a link is right-clicked and they always have to be collapsed. I'd say the single link menu is used more frequently, and it should not be hidden in the submenu to workaround a Firefox bug.

**Comment by Onurtag** [comment] 2019-07-25 22:44
That image above looks pretty awesome.  
It might be possible to keep it as a single button if it is possible to do something like:  
- If there are any links selected, show the above popup
- If nothing is selected just download the right clicked url  (like the current version)  

It can also be an option to show the above popup to always show even if you didn't select anything.

---


As for dark mode option;  
When you are ready to release the new version, I can fix the above css to make it work with the new version on an unreleased build. (if you need a helping hand)

**Comment by jingyu9575** [comment] 2019-07-26 02:24
@Onurtag

> If there are any links selected, show the above popup

I think it is a good idea. The menus have been merged in this way. The bug mentioned above cannot be solved though.

> fix the above css to make it work with the new version

Thank you, I'd appreciate it if you can update the CSS for v2. 
The repo has been updated with the v2 code, and the extension XPI is [here](https://github.com/jingyu9575/multithreaded-download-manager/releases/tag/v2.0a1). It is unsigned and can only be installed temporarily, or in Developer Edition/Nightly/Unbranded build after disabling mandatory signing. Since there are changes in the connection APIs, I'd test it for some more time before releasing to Mozilla Add-ons.

**Comment by Onurtag** [comment] 2019-07-26 09:14
This is what I made for now. The margins were just extras, theres nothing to add to the main .css files.
https://gist.github.com/Onurtag/21fd4ada8bb583c3f2c0ad32dcb21e4d  
I'll take another look this sunday to confirm that its good enough.  

I'm not really a designer so if you have better ideas for colors etc. go ahead and fix them up before adding it in as an option.

**Comment by mrochaaa** [comment] 2019-07-26 13:10
@jingyu9575, I say about Foxy Link not because context menu, I say about Foxy Link because "seem" which this plugin work well when an image is at the beginning of the selection, or not?

**Comment by jingyu9575** [comment] 2019-07-27 00:35
@Onurtag: The CSS has been included as a theme option. You can edit the [source file](https://github.com/jingyu9575/multithreaded-download-manager/blob/master/src/common/theme/dark.styl) and create a pull request if you want changes. (The symbols `{};` are not required in that file.)


---

@mrochaaa: FoxyLink is also affected by the same problem; the "Open Selected links" menu item does not show when the bug happens. The bug seems to happen only when there is an image just before the selection, but not inside the selection.

![图片](https://user-images.githubusercontent.com/8923139/61987384-b1e1a600-b048-11e9-8899-e1fbe0d6b59e.png)

**Closed by jingyu9575** 2019-07-27 00:35 UTC
Labels: enhancement
